
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - games.vlad.io
  resources:
  - tictactoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - games.vlad.io
  resources:
  - tictactoes/finalizers
  verbs:
  - update
- apiGroups:
  - games.vlad.io
  resources:
  - tictactoes/status
  verbs:
  - get
  - patch
  - update
