# permissions for end users to edit tictactoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tictactoe-editor-role
rules:
- apiGroups:
  - games.vlad.io
  resources:
  - tictactoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - games.vlad.io
  resources:
  - tictactoes/status
  verbs:
  - get
